### ISSUE TITLE
Add "saved reply" for PR review 

### ISSUE THREAD

**Issue by AnilMistry** [GSTT-CSC/project-template#31]
To ensure that code is reviewed by the criteria set out in "CSC PR.0017 Reviewing Github Pull Requests", a *saved reply* should be added to the project template, providing a checklist of items. 
eg.
- [x] Implements change request
- [x] Consistent with software system design
- [x] Documentation: Description of why fufilled, insufficient, or not needed.
- [ ] Unit Tests: Ditto
- [ ] Risk Assessment: Ditto
- [ ] Integration Tests: Ditto

**Comment by laurencejackson** [comment]
I think this has to be done at a user level. I've added the saved reply to my own, but i think we'll need to ask everyone to do it themselves. 

I'm going to close this issue as unrelated to the repository
